version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app  

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
      
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
